---
- name: Update Cloudflare DNS records
  hosts: host
  vars:
    cloudflare_api_endpoint: "https://api.cloudflare.com/client/v4"

  tasks:
    - name: Get current external IP
      uri:
        url: "https://api.ipify.org?format=json"
        return_content: yes
      register: external_ip_response

    - name: Extract external IP
      set_fact:
        current_external_ip: "{{ external_ip_response.json.ip }}"

    - name: Print current external IP
      debug:
        msg: "Current external IP: {{ current_external_ip }}"

    - name: Get current A record 
      uri:
        url: "{{ cloudflare_api_endpoint }}/zones/{{ cloudflare_zone_id }}/dns_records/{{ cloudflare_a_record_id }}"
        headers:
          Authorization: "Bearer {{ cloudflare_api_key }}"
          Content-Type: "application/json"
      register: a_record_response

    - name: Extract current A record IP
      set_fact:
        current_a_record_ip: "{{ a_record_response.json.result.content }}"

    - name: Print current A record IP
      debug:
        msg: "Current A record IP: {{ current_a_record_ip }}"

    - name: Check if IP update is needed
      set_fact:
        update_needed: "{{ current_external_ip != current_a_record_ip }}"

    - name: Update A record
      uri:
        url: "{{ cloudflare_api_endpoint }}/zones/{{ cloudflare_zone_id }}/dns_records/{{ cloudflare_a_record_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ cloudflare_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "A"
          name: "{{ a_record_name }}"
          content: "{{ current_external_ip }}"
          ttl: 1
          proxied: false
      when: update_needed

    - name: Update TXT record
      uri:
        url: "{{ cloudflare_api_endpoint }}/zones/{{ cloudflare_zone_id }}/dns_records/{{ cloudflare_txt_record_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ cloudflare_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "TXT"
          name: "{{ txt_record_name }}"
          content: "{{ current_external_ip }}"
          ttl: 1
      when: update_needed

    - name: Print update status
      debug:
        msg: "{{ 'DNS records updated successfully.' if update_needed else 'No update needed. DNS records are already up to date.' }}"
