---
- name: Add cron jobs for package updates and autoremove
  hosts: pies
  become: yes
  tasks:
    - name: Schedule apt update and upgrade every Monday at 3 AM
      ansible.builtin.cron:
        name: "upgrade packages"
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "1"
        job: "sudo apt update && sudo apt upgrade -y"

    - name: Schedule apt autoremove every Monday at 4 AM
      ansible.builtin.cron:
        name: "Autoremove packages"
        minute: "0"
        hour: "4"
        day: "*"
        month: "*"
        weekday: "1"
        job: "sudo apt autoremove"
