#
#This will update and install only the security updates
#https://github.com/adithyakhamithkar/ansible-playbooks/blob/master/install-security-updates.yml
#
---
- hosts: '{{inventory}}'
  become: yes

  tasks:
  - name: Make a copy of security repos
    shell: cat /etc/apt/sources.list|grep secu >/etc/apt/security.sources.list

  - name: Update cache
    apt: update_cache=yes

  - name: Install security updates
    shell: apt-get upgrade -oDir::Etc::SourceList=/etc/apt/security.sources.list --force-yes -y
