---
- name: Patch and reboot servers
  hosts: pies
  become: yes
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Reboot server if required
      ansible.builtin.reboot:
        msg: "Rebooting after patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
