---
- name: Update and upgrade packages on Ubuntu/Debian servers
  hosts: pies
  become: true
  become_user: root
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Run apt upgrade -y
      ansible.builtin.shell:
        cmd: sudo apt upgrade -y

    - name: Reboot server if required
      ansible.builtin.reboot:
        msg: "Rebooting after patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

