---
- name: Update Pi-hole
  hosts: host
  become: yes
  become_method: sudo
  become_user: root 
  tasks:

    - name: Remove dpkg lock-frontend
      ansible.builtin.file:
        path: /var/lib/dpkg/lock-frontend
        state: absent
      become: yes

    - name: Update Pi-hole
      ansible.builtin.command: pihole -up

