---
- name: Update and upgrade packages on Ubuntu/Debian servers
  hosts: pies
  become: true
  become_user: root
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot server if required
      ansible.builtin.reboot:
        msg: "Rebooting after patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
