---
- name: Add SSH key and disable password authentication
  hosts: host
  become: yes
  become_method: su
  become_user: root 

  vars:
    ssh_key: "{{ lookup('env', 'SSH_KEY') }}"
    target_user: "{{ lookup('env', 'TARGET_USER') }}"

  tasks:
    - name: Add SSH key to the specified user
      ansible.posix.authorized_key:
        user: "{{ target_user }}"
        key: "{{ ssh_key }}"

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
        - Restart SSH service

    - name: Disable SSH challenge-response authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present
      notify:
        - Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
