---
- name: Update Ubuntu servers
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root 
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Clean up unnecessary packages
      apt:
        autoremove: yes
