---
- name: Update, Upgrade and Reboot all ubuntu servers on Pi
  hosts: host
  become: yes
  become_method: sudo
  become_user: root 
  tasks:

    - name: Remove dpkg lock-frontend
      ansible.builtin.file:
        path: /var/lib/dpkg/lock-frontend
        state: absent
      become: yes
      
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Clean up unnecessary packages
      apt:
        autoremove: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
