---
- name: Update and upgrade packages on Ubuntu servers
  hosts: pies
  become: true
  tasks:
   - name: apt update
     ansible.builtin.apt:
       update_cache: yes

   - name: apt upgrade
     environment:
       DEBIAN_FRONTEND: noninteractive
     ansible.builtin.apt:
       upgrade: 'yes'

   - name: Check if a reboot is required
     ansible.builtin.stat:
       path: /var/run/reboot-required
       get_md5: no
     register: reboot_required_file

   - name: Reboot the server (if required)
     ansible.builtin.reboot:
     when: reboot_required_file.stat.exists == true

   - name: Remove dependencies that are no longer required
     ansible.builtin.apt:
       autoremove: yes
