---
- name: Update and upgrade packages on Ubuntu/Debian servers
  hosts: pies
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400

    

