---
- name: Allow ansible_user to run sudo commands without a password
  hosts: all
  become: yes
  tasks:
    - name: Add ansible_user to sudoers with NOPASSWD
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible_user'
        line: 'ansible_user ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
